use LouvreDatabase
	
	DECLARE @tableName NVARCHAR(50) = ''

	SELECT
		C.COLUMN_NAME,
		CASE
			WHEN PK.COLUMN_NAME IS NOT NULL THEN 'PrimaryKey'
			WHEN FK.COLUMN_NAME IS NOT NULL THEN 'ForeignKey'
			ELSE 'RegularColumn'
		END AS ColumnType,
		C.TABLE_SCHEMA,
		T.TABLE_TYPE,
		C.IS_NULLABLE,
		C.DATA_TYPE,
		C.ORDINAL_POSITION,
		FK.ReferencedTableName AS ReferencedTableName,
		FK.ReferencedColumnName AS ReferencedColumnName
	FROM
		INFORMATION_SCHEMA.COLUMNS AS C
	JOIN
		INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME
	LEFT JOIN
		(
		SELECT
			CU.COLUMN_NAME,
			PK.TABLE_NAME AS ReferencedTableName,
			PT.COLUMN_NAME AS ReferencedColumnName
		FROM
			INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC
		INNER JOIN
			INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS FK ON RC.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
		INNER JOIN
			INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS PK ON RC.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
		INNER JOIN
			INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS CU ON RC.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
		INNER JOIN
			(
			SELECT
				i1.TABLE_NAME,
				i2.COLUMN_NAME
			FROM
				INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS i1
			INNER JOIN
				INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS i2 ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
			WHERE
				i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
			) AS PT ON PT.TABLE_NAME = PK.TABLE_NAME
		WHERE
			FK.TABLE_NAME = @tableName
			AND FK.CONSTRAINT_TYPE = 'FOREIGN KEY'
		) AS FK ON C.COLUMN_NAME = FK.COLUMN_NAME
	LEFT JOIN
		INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS PK ON C.COLUMN_NAME = PK.COLUMN_NAME
			AND PK.TABLE_NAME = @tableName
			AND PK.CONSTRAINT_NAME LIKE 'PK%'
	WHERE
		C.TABLE_NAME = @tableName
	ORDER BY
		C.ORDINAL_POSITION;